version: '3.3'

services:
    testnet:
        build: .
        restart: always
        entrypoint: ./scripts/docker-entry.sh
        environment:
            COMETA_ENVIRONMENT: "testnet"
            REACH_NO_WARN: "true"
        volumes:
            - .:/app
        ports:
            - "5001:5001"
        depends_on:
            - mongodb-testnet

    mongodb-testnet:
        image: mongo
        restart: always
