version: '3.3'

services:
    mainnet:
        build: .
        restart: always
        entrypoint: ./scripts/docker-entry.sh
        environment:
            COMETA_ENVIRONMENT: "mainnet"
            REACH_NO_WARN: "true"
        volumes:
            - .:/app
        ports:
            - "5000:5000"
        depends_on:
            - mongodb-mainnet

    mongodb-mainnet:
        image: mongo
        restart: always
        volumes:
            - "mongodb-mainnet:/data/db"

volumes:
    mongodb-mainnet:
