version: '3.3'

services:
    app:
        build: .
        restart: always
        entrypoint: ./scripts/docker-entry.sh
        environment:
            REACH_NO_WARN: "${REACH_NO_WARN}"
        volumes:
            - .:/app
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        depends_on:
            - mongodb

    bot:
        build: .
        restart: always
        entrypoint: scripts/run_bot.sh
        environment:
            PYTHONUNBUFFERED: 1
        volumes:
            - .:/app
        depends_on:
            - mongodb
        profiles:
            - "mainnet"

    mongodb:
        image: mongo
        restart: always
        command: mongod --port ${MONGODB_PORT}
        volumes:
            - "/var/lib/mongodb-${ALGO_NETWORK}:/data/db"
