version: '3.3'

services:
    prod:
        build: .
        restart: always
        entrypoint: ./scripts/docker-entry.sh
        environment:
            COMETA_ENVIRONMENT: "prod"
            REACH_NO_WARN: "true"
        volumes:
            - .:/app
        ports:
            - "5000:5000"
        network_mode: host

    test:
        build: .
        restart: always
        entrypoint: ./scripts/docker-entry.sh
        environment:
            COMETA_ENVIRONMENT: "test"
            REACH_NO_WARN: "true"
        volumes:
            - .:/app
        ports:
            - "5001:5001"
        network_mode: host